import { Inter, Mulish } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import { Roboto } from "next/font/google";
import Footer from "./components/Footer";

const mulish = Mulish({ subsets: ["latin"], weigth: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={mulish.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
